- name: gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    
## TUNING
- ansible.builtin.import_tasks: system_performance_tuning.yml
 
- name: flush handlers before continuing
  meta: flush_handlers
	
# Assurer que le premier noeud est up avant d'ajouter un utilisateur	 
- name: "ensure {{ mariadb_systemd_service_name }} is started on first node"
  ansible.builtin.service:
    name: "{{ mariadb_systemd_service_name }}"
    state: "started"
  become: true
  when: inventory_hostname == galera_mysql_first_node
  
- ansible.builtin.import_tasks: mysql_users.yml

- ansible.builtin.import_tasks: setup_cluster.yml

- ansible.builtin.import_tasks: configure_root_access.yml

## A VOIR A QUOI SERT CETTE ETAPE
- ansible.builtin.import_tasks: mysql_databases.yml
  tags:
    - mysql_databases
  when:
    - mariadb_databases | count > 0
    - inventory_hostname == galera_mysql_first_node
    
## MONITORING ? 
- ansible.builtin.import_tasks: galera_monitoring.yml
  tags:
    - config_galera_monitoring
  when: galera_enable_galera_monitoring_script|bool

- ansible.builtin.import_tasks: cacti.yml
  tags:
    - config_cacti_monitoring
  when: galera_enable_cacti_monitoring
